;; NOTE: Assertions have been generated by update_lit_checks.py and should not be edited.
;; RUN: wasm-opt %s --load-store-forwarding -all -S -o - | filecheck %s

(module
 ;; $B is a subtype of $A. $C is unrelated to both, but shares the same first
 ;; field, so writes to it can never alias writes to $A or $B.
 ;; CHECK:      (type $A (sub (struct (field (mut i32)) (field (mut i32)))))
 (type $A (sub (struct (field (mut i32)) (field (mut i32)))))
 ;; CHECK:      (type $refs (sub (struct (field (mut (ref null $A))))))

 ;; CHECK:      (type $packed (struct (field (mut i8))))

 ;; CHECK:      (type $B (sub $A (struct (field (mut i32)) (field (mut i32)))))
 (type $B (sub $A (struct (field (mut i32)) (field (mut i32)))))
 ;; CHECK:      (type $C (struct (field (mut i32))))
 (type $C (struct (field (mut i32))))

 (type $packed (struct (field (mut i8))))

 (type $refs (sub (struct (field (mut (ref null $A))))))

 ;; CHECK:      (import "env" "import" (func $import (type $9)))
 (import "env" "import" (func $import))
 ;; CHECK:      (import "env" "import-i32" (func $import-i32 (type $6) (result i32)))
 (import "env" "import-i32" (func $import-i32 (result i32)))

 ;; CHECK:      (tag $e (type $9))
 (tag $e)

 ;; The stored local value is forwarded to the load.
 ;; CHECK:      (func $forward-local (type $1) (param $ref (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $value)
 ;; CHECK-NEXT: )
 (func $forward-local (param $ref (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (local.get $value)
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; The stored constant is forwarded to the load.
 ;; CHECK:      (func $forward-const (type $10) (param $ref (ref $A)) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (i32.const 42)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (i32.const 42)
 ;; CHECK-NEXT: )
 (func $forward-const (param $ref (ref $A)) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (i32.const 42)
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; One store can be forwarded to multiple loads, and loads do not invalidate
 ;; anything.
 ;; CHECK:      (func $forward-twice (type $1) (param $ref (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (i32.add
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $forward-twice (param $ref (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (local.get $value)
  )
  (i32.add
   (struct.get $A 0
    (local.get $ref)
   )
   (struct.get $A 0
    (local.get $ref)
   )
  )
 )

 ;; A second store to the same field overwrites: the latest value is
 ;; forwarded.
 ;; CHECK:      (func $forward-latest (type $1) (param $ref (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $value)
 ;; CHECK-NEXT: )
 (func $forward-latest (param $ref (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (i32.const 1)
  )
  (struct.set $A 0
   (local.get $ref)
   (local.get $value)
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; The load is of a different field, so nothing is forwarded.
 ;; CHECK:      (func $no-forward-other-field (type $1) (param $ref (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 1
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-forward-other-field (param $ref (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (local.get $value)
  )
  (struct.get $A 1
   (local.get $ref)
  )
 )

 ;; The load is through a different local (which might refer to a different
 ;; object), so nothing is forwarded.
 ;; CHECK:      (func $no-forward-other-local (type $7) (param $x (ref $A)) (param $y (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 0
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-forward-other-local (param $x (ref $A)) (param $y (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $x)
   (local.get $value)
  )
  (struct.get $A 0
   (local.get $y)
  )
 )

 ;; A store through another reference of the same type may write to the same
 ;; object, invalidating what we know about the first store.
 ;; CHECK:      (func $invalidate-aliasing-store (type $7) (param $x (ref $A)) (param $y (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 0
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $invalidate-aliasing-store (param $x (ref $A)) (param $y (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $x)
   (local.get $value)
  )
  (struct.set $A 0
   (local.get $y)
   (i32.const 1)
  )
  (struct.get $A 0
   (local.get $x)
  )
 )

 ;; The same, with a store through a reference of a subtype: it may still
 ;; alias, so nothing is forwarded.
 ;; CHECK:      (func $invalidate-subtype-store (type $12) (param $x (ref $A)) (param $y (ref $B)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.set $B 0
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 0
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $invalidate-subtype-store (param $x (ref $A)) (param $y (ref $B)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $x)
   (local.get $value)
  )
  (struct.set $B 0
   (local.get $y)
   (i32.const 1)
  )
  (struct.get $A 0
   (local.get $x)
  )
 )

 ;; A possibly-aliasing store to a *different* field does not interfere, and
 ;; we still forward.
 ;; CHECK:      (func $forward-past-other-field-store (type $7) (param $x (ref $A)) (param $y (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.set $A 1
 ;; CHECK-NEXT:   (local.get $y)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $value)
 ;; CHECK-NEXT: )
 (func $forward-past-other-field-store (param $x (ref $A)) (param $y (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $x)
   (local.get $value)
  )
  (struct.set $A 1
   (local.get $y)
   (i32.const 1)
  )
  (struct.get $A 0
   (local.get $x)
  )
 )

 ;; A store through a reference of an unrelated type cannot alias, and we
 ;; still forward.
 ;; CHECK:      (func $forward-past-unrelated-store (type $13) (param $x (ref $A)) (param $z (ref $C)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $x)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.set $C 0
 ;; CHECK-NEXT:   (local.get $z)
 ;; CHECK-NEXT:   (i32.const 1)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $value)
 ;; CHECK-NEXT: )
 (func $forward-past-unrelated-store (param $x (ref $A)) (param $z (ref $C)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $x)
   (local.get $value)
  )
  (struct.set $C 0
   (local.get $z)
   (i32.const 1)
  )
  (struct.get $A 0
   (local.get $x)
  )
 )

 ;; A call may write to the field, so nothing is forwarded.
 ;; CHECK:      (func $invalidate-call (type $1) (param $ref (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (call $import)
 ;; CHECK-NEXT:  (struct.get $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $invalidate-call (param $ref (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (local.get $value)
  )
  (call $import)
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; The reference local is written in between, so the load may be of another
 ;; object, and nothing is forwarded.
 ;; CHECK:      (func $invalidate-ref-local-set (type $7) (param $ref (ref $A)) (param $other (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $ref
 ;; CHECK-NEXT:   (local.get $other)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $invalidate-ref-local-set (param $ref (ref $A)) (param $other (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (local.get $value)
  )
  (local.set $ref
   (local.get $other)
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; The local the stored value was read from is written in between, so we can
 ;; no longer repeat it, and nothing is forwarded.
 ;; CHECK:      (func $invalidate-value-local-set (type $1) (param $ref (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $value
 ;; CHECK-NEXT:   (i32.const 9)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $invalidate-value-local-set (param $ref (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (local.get $value)
  )
  (local.set $value
   (i32.const 9)
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; The store only happens on one path to the load, so nothing is forwarded.
 ;; CHECK:      (func $no-forward-past-merge (type $2) (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (local.get $cond)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (struct.set $A 0
 ;; CHECK-NEXT:     (local.get $ref)
 ;; CHECK-NEXT:     (local.get $value)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-forward-past-merge (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
  (if
   (local.get $cond)
   (then
    (struct.set $A 0
     (local.get $ref)
     (local.get $value)
    )
   )
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; The store dominates the load in the if arm, so we forward.
 ;; CHECK:      (func $forward-into-if (type $2) (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (local.get $cond)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (return
 ;; CHECK-NEXT:     (local.get $value)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (i32.const 0)
 ;; CHECK-NEXT: )
 (func $forward-into-if (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (local.get $value)
  )
  (if
   (local.get $cond)
   (then
    (return
     (struct.get $A 0
      (local.get $ref)
     )
    )
   )
  )
  (i32.const 0)
 )

 ;; The store also dominates the load past a br_if, so we forward.
 ;; CHECK:      (func $forward-past-br-if (type $2) (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
 ;; CHECK-NEXT:  (block $out
 ;; CHECK-NEXT:   (struct.set $A 0
 ;; CHECK-NEXT:    (local.get $ref)
 ;; CHECK-NEXT:    (local.get $value)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $out
 ;; CHECK-NEXT:    (local.get $cond)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (return
 ;; CHECK-NEXT:    (local.get $value)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (i32.const 0)
 ;; CHECK-NEXT: )
 (func $forward-past-br-if (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
  (block $out
   (struct.set $A 0
    (local.get $ref)
    (local.get $value)
   )
   (br_if $out
    (local.get $cond)
   )
   (return
    (struct.get $A 0
     (local.get $ref)
    )
   )
  )
  (i32.const 0)
 )

 ;; The stored value flows into the loop, and around its backedge: nothing in
 ;; the loop can change the field, so both loads are forwarded.
 ;; CHECK:      (func $forward-into-loop (type $2) (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $loop
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (local.get $value)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $loop
 ;; CHECK-NEXT:    (local.get $cond)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $value)
 ;; CHECK-NEXT: )
 (func $forward-into-loop (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (local.get $value)
  )
  (loop $loop
   (drop
    (struct.get $A 0
     (local.get $ref)
    )
   )
   (br_if $loop
    (local.get $cond)
   )
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; The loop stores to the field, so the load in it sees a different value on
 ;; later iterations, and is not forwarded. But the load after the loop is
 ;; forwarded: every path to it passes through the store of 7 last.
 ;; CHECK:      (func $no-forward-loop-invalidated (type $2) (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (loop $loop
 ;; CHECK-NEXT:   (drop
 ;; CHECK-NEXT:    (struct.get $A 0
 ;; CHECK-NEXT:     (local.get $ref)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (struct.set $A 0
 ;; CHECK-NEXT:    (local.get $ref)
 ;; CHECK-NEXT:    (i32.const 7)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $loop
 ;; CHECK-NEXT:    (local.get $cond)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (i32.const 7)
 ;; CHECK-NEXT: )
 (func $no-forward-loop-invalidated (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (local.get $value)
  )
  (loop $loop
   (drop
    (struct.get $A 0
     (local.get $ref)
    )
   )
   (struct.set $A 0
    (local.get $ref)
    (i32.const 7)
   )
   (br_if $loop
    (local.get $cond)
   )
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; The stored value survives an if whose arms do nothing dangerous, and the
 ;; load after it is forwarded.
 ;; CHECK:      (func $forward-past-if (type $2) (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
 ;; CHECK-NEXT:  (local $scratch i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (local.get $cond)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (local.set $scratch
 ;; CHECK-NEXT:     (i32.const 1)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (else
 ;; CHECK-NEXT:    (local.set $scratch
 ;; CHECK-NEXT:     (i32.const 2)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $value)
 ;; CHECK-NEXT: )
 (func $forward-past-if (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
  (local $scratch i32)
  (struct.set $A 0
   (local.get $ref)
   (local.get $value)
  )
  (if
   (local.get $cond)
   (then
    (local.set $scratch
     (i32.const 1)
    )
   )
   (else
    (local.set $scratch
     (i32.const 2)
    )
   )
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; One arm of the if writes to the field through a possibly-aliasing
 ;; reference, so the paths disagree after the if and nothing is forwarded.
 ;; CHECK:      (func $no-forward-past-if-invalidating (type $14) (param $ref (ref $A)) (param $other (ref $A)) (param $value i32) (param $cond i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (local.get $cond)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (struct.set $A 0
 ;; CHECK-NEXT:     (local.get $other)
 ;; CHECK-NEXT:     (i32.const 7)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-forward-past-if-invalidating (param $ref (ref $A)) (param $other (ref $A)) (param $value i32) (param $cond i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (local.get $value)
  )
  (if
   (local.get $cond)
   (then
    (struct.set $A 0
     (local.get $other)
     (i32.const 7)
    )
   )
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; Both arms of the if store the same value to the same field, so the load
 ;; after the merge is forwarded.
 ;; CHECK:      (func $forward-merge-same-value (type $1) (param $ref (ref $A)) (param $cond i32) (result i32)
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (local.get $cond)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (struct.set $A 0
 ;; CHECK-NEXT:     (local.get $ref)
 ;; CHECK-NEXT:     (i32.const 42)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (else
 ;; CHECK-NEXT:    (struct.set $A 0
 ;; CHECK-NEXT:     (local.get $ref)
 ;; CHECK-NEXT:     (i32.const 42)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (i32.const 42)
 ;; CHECK-NEXT: )
 (func $forward-merge-same-value (param $ref (ref $A)) (param $cond i32) (result i32)
  (if
   (local.get $cond)
   (then
    (struct.set $A 0
     (local.get $ref)
     (i32.const 42)
    )
   )
   (else
    (struct.set $A 0
     (local.get $ref)
     (i32.const 42)
    )
   )
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; The arms store different values, so nothing is forwarded after the merge.
 ;; CHECK:      (func $no-forward-merge-different-values (type $1) (param $ref (ref $A)) (param $cond i32) (result i32)
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (local.get $cond)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (struct.set $A 0
 ;; CHECK-NEXT:     (local.get $ref)
 ;; CHECK-NEXT:     (i32.const 42)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (else
 ;; CHECK-NEXT:    (struct.set $A 0
 ;; CHECK-NEXT:     (local.get $ref)
 ;; CHECK-NEXT:     (i32.const 43)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-forward-merge-different-values (param $ref (ref $A)) (param $cond i32) (result i32)
  (if
   (local.get $cond)
   (then
    (struct.set $A 0
     (local.get $ref)
     (i32.const 42)
    )
   )
   (else
    (struct.set $A 0
     (local.get $ref)
     (i32.const 43)
    )
   )
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; A throw transfers control without changing any fields, so the stored
 ;; value flows into the catch and the load there is forwarded.
 ;; CHECK:      (func $forward-into-catch (type $1) (param $ref (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (block $catch
 ;; CHECK-NEXT:   (try_table (catch_all $catch)
 ;; CHECK-NEXT:    (struct.set $A 0
 ;; CHECK-NEXT:     (local.get $ref)
 ;; CHECK-NEXT:     (local.get $value)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (throw $e)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $value)
 ;; CHECK-NEXT: )
 (func $forward-into-catch (param $ref (ref $A)) (param $value i32) (result i32)
  (block $catch
   (try_table (catch_all $catch)
    (struct.set $A 0
     (local.get $ref)
     (local.get $value)
    )
    (throw $e)
   )
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; Here the catch is reached by a call, which might have written to the
 ;; field before throwing, so nothing is forwarded (on the normal path out of
 ;; the try as well).
 ;; CHECK:      (func $no-forward-into-catch-call (type $1) (param $ref (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (block $catch
 ;; CHECK-NEXT:   (try_table (catch_all $catch)
 ;; CHECK-NEXT:    (struct.set $A 0
 ;; CHECK-NEXT:     (local.get $ref)
 ;; CHECK-NEXT:     (local.get $value)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:    (call $import)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-forward-into-catch-call (param $ref (ref $A)) (param $value i32) (result i32)
  (block $catch
   (try_table (catch_all $catch)
    (struct.set $A 0
     (local.get $ref)
     (local.get $value)
    )
    (call $import)
   )
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; Constants in a struct.new are forwarded to loads of the local it is
 ;; assigned to.
 ;; CHECK:      (func $forward-new-const (type $6) (result i32)
 ;; CHECK-NEXT:  (local $ref (ref null $A))
 ;; CHECK-NEXT:  (local.set $ref
 ;; CHECK-NEXT:   (struct.new $A
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:    (i32.const 2)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (i32.const 2)
 ;; CHECK-NEXT: )
 (func $forward-new-const (result i32)
  (local $ref (ref null $A))
  (local.set $ref
   (struct.new $A
    (i32.const 1)
    (i32.const 2)
   )
  )
  (struct.get $A 1
   (local.get $ref)
  )
 )

 ;; The zero default of a struct.new_default is forwarded.
 ;; CHECK:      (func $forward-new-default (type $6) (result i32)
 ;; CHECK-NEXT:  (local $ref (ref null $A))
 ;; CHECK-NEXT:  (local.set $ref
 ;; CHECK-NEXT:   (struct.new_default $A)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (i32.const 0)
 ;; CHECK-NEXT: )
 (func $forward-new-default (result i32)
  (local $ref (ref null $A))
  (local.set $ref
   (struct.new_default $A)
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; A non-constant struct.new operand is not forwarded (a later operand could
 ;; have changed the local before the allocation is assigned).
 ;; CHECK:      (func $no-forward-new-local (type $15) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (local $ref (ref null $A))
 ;; CHECK-NEXT:  (local.set $ref
 ;; CHECK-NEXT:   (struct.new $A
 ;; CHECK-NEXT:    (local.get $value)
 ;; CHECK-NEXT:    (i32.const 2)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-forward-new-local (param $value i32) (result i32)
  (local $ref (ref null $A))
  (local.set $ref
   (struct.new $A
    (local.get $value)
    (i32.const 2)
   )
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; The stored value is truncated when written to a packed field, so nothing
 ;; is forwarded.
 ;; CHECK:      (func $no-forward-packed (type $16) (param $ref (ref $packed)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $packed 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get_u $packed 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-forward-packed (param $ref (ref $packed)) (param $value i32) (result i32)
  (struct.set $packed 0
   (local.get $ref)
   (local.get $value)
  )
  (struct.get_u $packed 0
   (local.get $ref)
  )
 )

 ;; But a packed field's zero default is unaffected by truncation, and is
 ;; forwarded.
 ;; CHECK:      (func $forward-packed-default (type $6) (result i32)
 ;; CHECK-NEXT:  (local $ref (ref null $packed))
 ;; CHECK-NEXT:  (local.set $ref
 ;; CHECK-NEXT:   (struct.new_default $packed)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (i32.const 0)
 ;; CHECK-NEXT: )
 (func $forward-packed-default (result i32)
  (local $ref (ref null $packed))
  (local.set $ref
   (struct.new_default $packed)
  )
  (struct.get_u $packed 0
   (local.get $ref)
  )
 )

 ;; The stored value is more refined than the field: forwarding it refines the
 ;; type of the load as well.
 ;; CHECK:      (func $forward-refined (type $17) (param $ref (ref $refs)) (param $value (ref $B)) (result anyref)
 ;; CHECK-NEXT:  (struct.set $refs 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.get $value)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $value)
 ;; CHECK-NEXT: )
 (func $forward-refined (param $ref (ref $refs)) (param $value (ref $B)) (result anyref)
  (struct.set $refs 0
   (local.get $ref)
   (local.get $value)
  )
  (struct.get $refs 0
   (local.get $ref)
  )
 )

 ;; The stored value cannot be repeated at the load, so it is captured in a
 ;; new local at the store, and the load reads that local.
 ;; CHECK:      (func $forward-complex (type $1) (param $ref (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (local $2 i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.tee $2
 ;; CHECK-NEXT:    (i32.add
 ;; CHECK-NEXT:     (local.get $value)
 ;; CHECK-NEXT:     (i32.const 1)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $2)
 ;; CHECK-NEXT: )
 (func $forward-complex (param $ref (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (i32.add
    (local.get $value)
    (i32.const 1)
   )
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; The same even when the stored value is a call: it executes once, in its
 ;; original position, and only the result is captured.
 ;; CHECK:      (func $forward-complex-call (type $10) (param $ref (ref $A)) (result i32)
 ;; CHECK-NEXT:  (local $1 i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.tee $1
 ;; CHECK-NEXT:    (call $import-i32)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $1)
 ;; CHECK-NEXT: )
 (func $forward-complex-call (param $ref (ref $A)) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (call $import-i32)
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; The captured value is immune to changes of the locals it was computed
 ;; from, unlike a plain local.get value (see $invalidate-value-local-set).
 ;; CHECK:      (func $forward-complex-past-source-change (type $1) (param $ref (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (local $2 i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.tee $2
 ;; CHECK-NEXT:    (i32.add
 ;; CHECK-NEXT:     (local.get $value)
 ;; CHECK-NEXT:     (i32.const 1)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.set $value
 ;; CHECK-NEXT:   (i32.const 9)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $2)
 ;; CHECK-NEXT: )
 (func $forward-complex-past-source-change (param $ref (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (i32.add
    (local.get $value)
    (i32.const 1)
   )
  )
  (local.set $value
   (i32.const 9)
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; Multiple loads share a single captured value.
 ;; CHECK:      (func $forward-complex-twice (type $1) (param $ref (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (local $2 i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.tee $2
 ;; CHECK-NEXT:    (i32.add
 ;; CHECK-NEXT:     (local.get $value)
 ;; CHECK-NEXT:     (i32.const 1)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (i32.add
 ;; CHECK-NEXT:   (local.get $2)
 ;; CHECK-NEXT:   (local.get $2)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $forward-complex-twice (param $ref (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (i32.add
    (local.get $value)
    (i32.const 1)
   )
  )
  (i32.add
   (struct.get $A 0
    (local.get $ref)
   )
   (struct.get $A 0
    (local.get $ref)
   )
  )
 )

 ;; No load wants this value, so we add no local and change nothing.
 ;; CHECK:      (func $no-tee-unused (type $1) (param $ref (ref $A)) (param $value i32) (result i32)
 ;; CHECK-NEXT:  (struct.set $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (i32.add
 ;; CHECK-NEXT:    (local.get $value)
 ;; CHECK-NEXT:    (i32.const 1)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 1
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-tee-unused (param $ref (ref $A)) (param $value i32) (result i32)
  (struct.set $A 0
   (local.get $ref)
   (i32.add
    (local.get $value)
    (i32.const 1)
   )
  )
  (struct.get $A 1
   (local.get $ref)
  )
 )

 ;; The arms store structurally identical values, but each would be captured
 ;; in its own local, so nothing is forwarded after the merge (compare with
 ;; $forward-merge-same-value, where the constants merge fine).
 ;; CHECK:      (func $no-forward-complex-merge (type $2) (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (local.get $cond)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (struct.set $A 0
 ;; CHECK-NEXT:     (local.get $ref)
 ;; CHECK-NEXT:     (i32.add
 ;; CHECK-NEXT:      (local.get $value)
 ;; CHECK-NEXT:      (i32.const 1)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (else
 ;; CHECK-NEXT:    (struct.set $A 0
 ;; CHECK-NEXT:     (local.get $ref)
 ;; CHECK-NEXT:     (i32.add
 ;; CHECK-NEXT:      (local.get $value)
 ;; CHECK-NEXT:      (i32.const 1)
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (struct.get $A 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $no-forward-complex-merge (param $ref (ref $A)) (param $value i32) (param $cond i32) (result i32)
  (if
   (local.get $cond)
   (then
    (struct.set $A 0
     (local.get $ref)
     (i32.add
      (local.get $value)
      (i32.const 1)
     )
    )
   )
   (else
    (struct.set $A 0
     (local.get $ref)
     (i32.add
      (local.get $value)
      (i32.const 1)
     )
    )
   )
  )
  (struct.get $A 0
   (local.get $ref)
  )
 )

 ;; A captured value of non-nullable reference type, forwarded across an if.
 ;; The tee structurally dominates the load here, so the new local can remain
 ;; non-nullable.
 ;; CHECK:      (func $forward-complex-ref (type $11) (param $ref (ref $refs)) (param $cond i32) (result anyref)
 ;; CHECK-NEXT:  (local $2 (ref (exact $A)))
 ;; CHECK-NEXT:  (struct.set $refs 0
 ;; CHECK-NEXT:   (local.get $ref)
 ;; CHECK-NEXT:   (local.tee $2
 ;; CHECK-NEXT:    (struct.new $A
 ;; CHECK-NEXT:     (i32.const 1)
 ;; CHECK-NEXT:     (i32.const 2)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (if
 ;; CHECK-NEXT:   (local.get $cond)
 ;; CHECK-NEXT:   (then
 ;; CHECK-NEXT:    (return
 ;; CHECK-NEXT:     (ref.null none)
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (local.get $2)
 ;; CHECK-NEXT: )
 (func $forward-complex-ref (param $ref (ref $refs)) (param $cond i32) (result anyref)
  (struct.set $refs 0
   (local.get $ref)
   (struct.new $A
    (i32.const 1)
    (i32.const 2)
   )
  )
  (if
   (local.get $cond)
   (then
    (return
     (ref.null none)
    )
   )
  )
  (struct.get $refs 0
   (local.get $ref)
  )
 )

 ;; Here the tee is inside a block that can be branched over, and the load is
 ;; after it: the load is still on every path (the store precedes the br_if),
 ;; but the new local does not structurally dominate it, so the non-nullable
 ;; local fixups that run after us make the local nullable and insert a
 ;; ref.as_non_null.
 ;; CHECK:      (func $forward-complex-ref-fixup (type $11) (param $ref (ref $refs)) (param $cond i32) (result anyref)
 ;; CHECK-NEXT:  (local $2 (ref null (exact $A)))
 ;; CHECK-NEXT:  (block $b
 ;; CHECK-NEXT:   (struct.set $refs 0
 ;; CHECK-NEXT:    (local.get $ref)
 ;; CHECK-NEXT:    (ref.as_non_null
 ;; CHECK-NEXT:     (local.tee $2
 ;; CHECK-NEXT:      (struct.new $A
 ;; CHECK-NEXT:       (i32.const 1)
 ;; CHECK-NEXT:       (i32.const 2)
 ;; CHECK-NEXT:      )
 ;; CHECK-NEXT:     )
 ;; CHECK-NEXT:    )
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:   (br_if $b
 ;; CHECK-NEXT:    (local.get $cond)
 ;; CHECK-NEXT:   )
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT:  (ref.as_non_null
 ;; CHECK-NEXT:   (local.get $2)
 ;; CHECK-NEXT:  )
 ;; CHECK-NEXT: )
 (func $forward-complex-ref-fixup (param $ref (ref $refs)) (param $cond i32) (result anyref)
  (block $b
   (struct.set $refs 0
    (local.get $ref)
    (struct.new $A
     (i32.const 1)
     (i32.const 2)
    )
   )
   (br_if $b
    (local.get $cond)
   )
  )
  (struct.get $refs 0
   (local.get $ref)
  )
 )
)
